/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameChallengeView {
  'id' : string,
  'status' : GameStatus,
  'timestamp' : bigint,
  'gameName' : string,
  'roomId' : string,
  'challenger' : string,
}
export type GameStatus = { 'pending' : null } |
  { 'denied' : null } |
  { 'accepted' : null };
export interface GameSessionView {
  'id' : string,
  'gameType' : string,
  'player1' : string,
  'player2' : [] | [string],
  'status' : string,
  'rpsMove1' : [] | [string],
  'rpsMove2' : [] | [string],
  'tttCells' : Array<[] | [string]>,
  'tttTurn' : bigint,
  'result' : [] | [string],
}
export interface Message {
  'username' : string,
  'text' : string,
  'voiceUrl' : [] | [string],
  'timestamp' : bigint,
}
export interface _SERVICE {
  'createGameChallenge' : ActorMethod<[string, string, string], string>,
  'createPrivateRoom' : ActorMethod<[string], boolean>,
  'createRPSChallenge' : ActorMethod<[string, string], string>,
  'getMatchResult' : ActorMethod<[string], [] | [string]>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getOnlineUsers' : ActorMethod<[string], Array<string>>,
  'getPendingChallenges' : ActorMethod<[string], Array<GameChallengeView>>,
  'getRPSGame' : ActorMethod<
    [string],
    [] | [
      {
        'id' : string,
        'status' : string,
        'result' : [] | [string],
        'move1' : [] | [string],
        'move2' : [] | [string],
        'player1' : string,
        'player2' : [] | [string],
        'roomId' : string,
      }
    ]
  >,
  'getRoomOnlineCount' : ActorMethod<[string], bigint>,
  'joinMatchmaking' : ActorMethod<[string], [] | [string]>,
  'joinRPSGame' : ActorMethod<[string, string], boolean>,
  'leaveMatchmaking' : ActorMethod<[string], undefined>,
  'login' : ActorMethod<[string, string], [] | [string]>,
  'logout' : ActorMethod<[string], undefined>,
  'playRPS' : ActorMethod<[string, string, string], undefined>,
  'register' : ActorMethod<[string, string], boolean>,
  'respondToChallenge' : ActorMethod<[string, string, boolean], boolean>,
  'roomExists' : ActorMethod<[string], boolean>,
  'sendMessage' : ActorMethod<
    [string, string, string, [] | [string]],
    undefined
  >,
  'updatePresence' : ActorMethod<[string, string], undefined>,
  'validateSession' : ActorMethod<[string], [] | [string]>,
  'getGameQueueMatch' : ActorMethod<[string], [] | [{ 'matchId' : string, 'opponent' : string }]>,
  'joinGameQueue' : ActorMethod<[string], [] | [{ 'matchId' : string, 'opponent' : string }]>,
  'leaveGameQueue' : ActorMethod<[string], undefined>,
  'createGameSession' : ActorMethod<[string, string, string], boolean>,
  'joinGameSession' : ActorMethod<[string, string], boolean>,
  'submitRPSMove' : ActorMethod<[string, string, string], undefined>,
  'submitTTTMove' : ActorMethod<[string, string, bigint], boolean>,
  'getGameSession' : ActorMethod<[string], [] | [GameSessionView]>,

}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];